### PR TITLE
issue/12 Added trim to remove spaces from ends of URL

### LINKED ISSUE #12: Source URL is not being trimmed for white space?
If you enter a source URL and include a space before the URL, it fails to load and in the console has the following:

TypeError: “ https://vimeo.com/000000000” is not a vimeo.com url.

So it just needs a wee trim perhaps?

Testing v 2.2.0

### PR DESCRIPTION
**Pull request by paul-mediakitchen**
fixes #12

### CODE REVIEW

**Review by oliverfoster — CHANGES_REQUESTED** [review]
Revert to 2 space indentation and it's good. 👍

**Review by oliverfoster — APPROVED** [review]

File: js/VimeoView.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default class VimeoView extends Backbone.View {
    */
   setupPlayer() {
     const options = {
-      url: this.model._source,
+      url: this.model._source.trim(),
```
Comment (oliverfoster) [inline js/VimeoView.js:35]:
```suggestion
      url: this.model._source?.trim(),
```
You may want to add the optional chaining operator in case the _source object isn't defined

File: js/adapt-vimeo.js [hunk 2]
```diff
@@ -114,7 +114,7 @@ class Vimeo extends ComponentView {
     Adapt.trigger('media', {
       isVideo: true,
       type: eventType,
-      src: this.model.get('_media')._source,
+      src: this.model.get('_media')._source.trim(),
```
Comment (oliverfoster) [inline js/adapt-vimeo.js:117]:
```suggestion
      src: this.model.get('_media')._source?.trim(),
```
You may want to add the optional chaining operator in case the _source object isn't defined

**Review by eleanor-heath — APPROVED** [review]

File: js/VimeoView.js (hunk 1 above)
Comment (cahirodoherty-learningpool) [reply js/VimeoView.js:35]: Hi Paul, if you use the 'commit suggestion' button above, I think this PR is then ready
