### PR TITLE
Wrap call to destroy in a try/catch

### LINKED ISSUE #9: Vimeo remove/destroy failing
### Subject of the issue/enhancement/features
Vimeo view remove call occasionally falling over

### Your environment
* FW5.7.0
* All browsers

There have been instances reported to us where the functionality of a course has been broken and upon investigating it can be seen that the VimeoView.remove method is failing to call `.destroy()` on the player. This is due to the _originalElement attribute not being present on the player

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
Perform a check for _originalElement attribute before calling destroy on the player

fixes #9 and [FW-2996](https://github.com/adaptlearning/adapt_framework/issues/2996)

### CODE REVIEW

**Review by ethan-lp — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

File: js/VimeoView.js [hunk 1]
```diff
@@ -93,7 +93,9 @@ define([
      */
     remove: function() {
       if (this.model._pauseWhenOffScreen) this.$el.off('inview.pauseWhenOffScreen');
-      this.player.destroy();
+
```
Comment (moloko) [inline js/VimeoView.js:96]:
```suggestion
      // fixes https://github.com/adaptlearning/adapt-vimeo/issues/9
```

**Comment by moloko** [comment]
Out of curiosity - what was happening when `_originalElement` wasn't present? If it was throwing an unhandled exception, might a try... catch be more appropriate?

**Comment by cahirodoherty-learningpool** [comment]
> Out of curiosity - what was happening when `_originalElement` wasn't present? If it was throwing an unhandled exception, might a try... catch be more appropriate?

Hi Matt, yeah it was causing an unhandled exception. Bit of a 'six of one...' in deciding whether to wrap it in a try catch or prevent it where possible. I'm happy with changing if you feel that's more appropriate.

**Comment by moloko** [comment]
> I'm happy with changing if you feel that's more appropriate.

My only thought was that using `try...catch` makes it immediately obvious what's going on... whereas the way it's written you'd really need to check the original issue to know why the check for `_originalElement` is necessary. 

If you don't mind I think it would be clearer to switch to `try...catch`?

**Review by moloko — APPROVED** [review]

**Comment by oliverfoster** [comment]
Do we know:

* What `_originalElement` is for
* Why it should be present for `destroy`
* Why / when `_originalElement` is not present
* Is there a memory leak when `destroy` fails, are their important event detachment / destruction tasks that are missed?

The `adaptView:preRemove` function can be helpful in situations where the element is removed from the DOM but needs to be in the DOM for removal.

Otherwise all looks fine.

**Comment by cahirodoherty-learningpool** [comment]
> * What `_originalElement` is for?
> * Why it should be present for `destroy`?
The `_originalElement` is expected by the vimeo.min.js destroy call and this falls over as a result when it is missing
> * Why / when `_originalElement` is not present?
I haven't been able to exactly track down how the player is still present, but the _originalElement has been removed
> * If there are any memory leaks when `destroy` fails, are their important event detachment / destruction tasks that are missed?
I'm not sure how to check this. Is there anywhere in particular I should pay attention to?
> The `adaptView:preRemove` function can be helpful in situations where the element is removed from the DOM but needs to be in the DOM for removal.

I am intending to continue debugging the exact scenario that is causing the issue, but would be keen to get this try/catch wrapper in to prevent a full course breaking as a result

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
#### Memory leaks

Could be, if javascript event handlers are attached to any dom node which is still part of the document for a player instance which should have been destroyed.

An example of this would be if a player instance was still reacting to window resize events, causing resize behaviours to execute after a failed destruction phase.

A memory leak could also be a global list of players attached to the global window context or to a library closure context, whereby a failed destruction phase leaves an reference to an instance of a player in a list where it shouldn't exist. This could prevent detached dom nodes and object instances from being garbage collected properly.

The only way of checking these types of leak is by walking through an unminified version of the vimeo code to check the logic of construction and destruction to find a solution which either doesn't involve a try/catch or at least verify that the try/catch has no adverse impact.
